---
kind: pipeline
type: kubernetes
name: RDS Secretsmanager Credential Sync

steps:
  - name: Build
    image: thegeeklab/drone-docker-buildx:20.11.3
    pull: if-not-exists
    settings:
      username:
        from_secret: username
      password:
        from_secret: password
      platforms: linux/amd64,linux/arm64/v8
      registry: "quay.io"
      repo: "quay.io/jlehtimaki/rscs"
      tags: ${DRONE_TAG}
trigger:
  event:
    - tag